### ISSUE TITLE
Brand box float style

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-theme-wp#244]
If the brand box is floated, it should be full width on mobile. See this [news article](https://library.ucdavis.edu/news/dr-gurdev-khush-celebrated-rice-breeder-donates-papers-to-uc-davis-library/) for badness.

Should remove the style attributes on the [twig file](https://github.com/UCDavisLibrary/ucdlib-theme-wp/blob/main/views/blocks/brand-textbox.twig), and make a few new css rules:
```css
@media (min-width: 768px) {
  .brand-textbox.u-align--right, .brand-textbox.u-align--left, ucd-theme-brand-textbox.u-align--right, ucd-theme-brand-textbox..u-align--left {
    max-width: 33%;
    min-width: auto;
  }
}
.brand-textbox.u-align--right, .brand-textbox.u-align--left, ucd-theme-brand-textbox.u-align--right, ucd-theme-brand-textbox..u-align--left {
  min-width: 100%;
}

```
